### ISSUE TITLE
Ortelius CLI | Pydantic | Import Error 'NoneIsAllowedError'

### ISSUE THREAD

**Issue by sachajw** [ortelius/ortelius#955]
During the build on Jenkins, when it tries to install `deployhub` it errors out with `import error NoneIsAllowedError`

```
+ pip install deployhub
Collecting deployhub
  Downloading deployhub-9.3.210-py3-none-any.whl.metadata (5.7 kB)
Collecting click (from deployhub)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting qtoml (from deployhub)
  Downloading qtoml-0.3.1-py3-none-any.whl.metadata (3.5 kB)
Collecting PyYAML (from deployhub)
  Downloading PyYAML-6.0.2-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (2.1 kB)
Collecting requests (from deployhub)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting configobj (from deployhub)
  Downloading configobj-5.0.8-py2.py3-none-any.whl.metadata (3.4 kB)
Collecting flatten-dict (from deployhub)
  Downloading flatten_dict-0.4.2-py2.py3-none-any.whl.metadata (9.2 kB)
Collecting pydantic (from deployhub)
  Downloading pydantic-2.9.1-py3-none-any.whl.metadata (146 kB)
Collecting certifi (from deployhub)
  Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting six (from configobj->deployhub)
  Downloading six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting annotated-types>=0.6.0 (from pydantic->deployhub)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.23.3 (from pydantic->deployhub)
  Downloading pydantic_core-2.23.3-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (6.6 kB)
Collecting typing-extensions>=4.6.1 (from pydantic->deployhub)
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting attrs<22.0,>=19.3.0 (from qtoml->deployhub)
  Downloading attrs-21.4.0-py2.py3-none-any.whl.metadata (9.8 kB)
Collecting charset-normalizer<4,>=2 (from requests->deployhub)
  Downloading charset_normalizer-3.3.2-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests->deployhub)
  Downloading idna-3.8-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests->deployhub)
  Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Downloading deployhub-9.3.210-py3-none-any.whl (40 kB)
Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
Downloading click-8.1.7-py3-none-any.whl (97 kB)
Downloading configobj-5.0.8-py2.py3-none-any.whl (36 kB)
Downloading flatten_dict-0.4.2-py2.py3-none-any.whl (9.7 kB)
Downloading pydantic-2.9.1-py3-none-any.whl (434 kB)
Downloading pydantic_core-2.23.3-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 5.6 MB/s eta 0:00:00
Downloading PyYAML-6.0.2-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (739 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 739.2/739.2 kB 4.9 MB/s eta 0:00:00
Downloading qtoml-0.3.1-py3-none-any.whl (12 kB)
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Downloading charset_normalizer-3.3.2-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (137 kB)
Downloading idna-3.8-py3-none-any.whl (66 kB)
Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
Installing collected packages: urllib3, typing-extensions, six, PyYAML, idna, click, charset-normalizer, certifi, attrs, annotated-types, requests, qtoml, pydantic-core, flatten-dict, configobj, pydantic, deployhub
Successfully installed PyYAML-6.0.2 annotated-types-0.7.0 attrs-21.4.0 certifi-2024.8.30 charset-normalizer-3.3.2 click-8.1.7 configobj-5.0.8 deployhub-9.3.210 flatten-dict-0.4.2 idna-3.8 pydantic-2.9.1 pydantic-core-2.23.3 qtoml-0.3.1 requests-2.32.3 six-1.16.0 typing-extensions-4.12.2 urllib3-2.2.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
+ git clone https://github.com/dstar55/docker-hello-world-spring-boot
Cloning into 'docker-hello-world-spring-boot'...
+ cd docker-hello-world-spring-boot
+ dh envscript --envvars component.toml --envvars_sh /home/jenkins/agent/workspace/ortelius-jenkins-demo-app_main/dhenv.sh
Traceback (most recent call last):
  File "/usr/local/bin/dh", line 179, in <module>
    from pydantic import NoneIsAllowedError
ImportError: cannot import name 'NoneIsAllowedError' from 'pydantic' (/usr/local/lib/python3.12/site-packages/pydantic/__init__.py)
```

**Comment by sbtaylor15** [comment]
@sachajw try `pip install ortelius-cli`

**Comment by sachajw** [comment]
The  `+ pip install ortelius-cli` worked, but the failure happens here now
```
+ dh envscript --envvars component.toml --envvars_sh /home/jenkins/agent/workspace/ortelius-jenkins-demo-app_main/dhenv.sh
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
```
```
Successfully installed annotated-types-0.7.0 attrs-21.4.0 certifi-2024.8.30 charset-normalizer-3.3.2 click-8.1.7 configobj-5.0.8 flatten-dict-0.4.2 idna-3.8 ortelius-cli-9.3.278 pydantic-2.9.1 pydantic-core-2.23.3 pyyaml-6.0.2 qtoml-0.3.1 requests-2.32.3 six-1.16.0 typing-extensions-4.12.2 urllib3-2.2.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
+ git clone https://github.com/dstar55/docker-hello-world-spring-boot
Cloning into 'docker-hello-world-spring-boot'...
+ cd docker-hello-world-spring-boot
+ dh envscript --envvars component.toml --envvars_sh /home/jenkins/agent/workspace/ortelius-jenkins-demo-app_main/dhenv.sh
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dh", line 1717, in <module>
    main()  # pyright: ignore [reportGeneralTypeIssues, reportCallIssue] # pylint: disable=no-value-for-parameter
    ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/dh", line 351, in main
    cookies = dhapi.login(dhurl, dhuser, dhpass, errors)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/deployhub/dhapi.py", line 209, in login
    data = result.json()
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0
```
